import { defineCollection, z } from 'astro:content';

// ── Projects ────────────────────────────────────────────────────────────────
const projects = defineCollection({
  type: 'content',
  schema: z.object({
    title:           z.string(),
    // slug is auto-generated by Astro from the filename; not in schema
    summary:         z.string().max(200),
    date:            z.coerce.date(),
    techStack:       z.array(z.string()),
    links: z
      .object({
        github: z.string().url().optional(),
        demo:   z.string().url().optional(),
        blog:   z.string().optional(),
      })
      .optional(),
    thumbnail:       z.string().optional(),
    featured:        z.boolean().default(false),
    stat:            z.string().optional(), // one-line impact metric for card display
    // Shared taxonomy across every project card — keep this list closed.
    tags: z
      .array(
        z.enum([
          'VISION',
          'GENERALIZATION',
          'EDGE DEPLOYMENT',
          'STATE ESTIMATION',
          'EVALUATION',
          'MULTIMODAL',
          'INFRASTRUCTURE',
        ])
      )
      .optional(),
    cardDescription: z.string().optional(), // longer recruiter-facing copy; overrides summary on card
    image:           z.string().optional(), // future: hero image path
    imageDark:       z.string().optional(), // future: dark mode image variant
  }),
});

// ── Writing ─────────────────────────────────────────────────────────────────
const writing = defineCollection({
  type: 'content',
  schema: z.object({
    title:    z.string(),
    // slug is auto-generated by Astro from the filename; not in schema
    date:     z.coerce.date(),
    summary:  z.string(),
    tags:     z.array(z.string()).optional(),
    category: z.enum(['tech', 'personal']).default('tech'),
    draft:    z.boolean().default(false), // excluded from the index and from getStaticPaths
    image:    z.string().optional(), // future: card or hero image
  }),
});

// ── Work ─────────────────────────────────────────────────────────────────────
const work = defineCollection({
  type: 'content',
  schema: z.object({
    org:         z.string(),
    role:        z.string(),
    startDate:   z.coerce.date(),
    // null = current role; omit field entirely for past roles
    endDate:     z.coerce.date().nullable().optional(),
    description: z.string(),
    techStack:   z.array(z.string()).optional(),
    location:    z.string().optional(),
  }),
});

export const collections = { projects, writing, work };
